// Firebase auth action types for user
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

// Firebase authstatechange
export const USER_IS_AUTHENTICATED = "USER_IS_AUTHENTICATED";
export const USER_IS_NOT_AUTHENTICATED = "USER_IS_NOT_AUTHENTICATED";

// Firestore get all documents
export const GET_ALL_ASTROPITCHES_SUCCESS = "GET_ALL_ASTROPITCHES_SUCCESS";
export const GET_ALL_ASTROPITCHES_ERROR = "GET_ALL_ASTROPITCHES_ERROR";

// Add to favorites
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";
export const ADD_TO_FAVORITES_ERROR = "ADD_TO_FAVORITES_ERROR";

// Get favorites
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_ERROR = "GET_FAVORITES_ERROR";

// Remove from favorites
export const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
export const REMOVE_FROM_FAVORITES_ERROR = "REMOVE_FROM_FAVORITES_ERROR";
